#!/bin/bash

HUE_IP=$(curl https://www.meethue.com/api/nupnp 2> /dev/null | jq -r ".[0].internalipaddress")
HUE_USER=erikvennink

PUSHOVER_TOKEN=azw2c2dw29x8o96ae2m2cp5gtx7mr4
PUSHOVER_USER=uPnTmp5puvngjiUYpGMGQ3AgUKjhgZ
PUSHOVER_NOTIFICATION_TITLE="Hue"
PUSHOVER_NOTIFICATION_MESSAGE_OK="Hue bridge settings updated!"
PUSHOVER_NOTIFICATION_MESSAGE_NOK="Hue bridge settings update failed!!!"

#GROUPS
GRP_WOONKAMER=1
GRP_KEUKEN=2
GRP_HAL=3
GRP_SLAAPKAMER=4
GRP_KANTOOR=5
GRP_TOILET=6
GRP_BADKAMER=7
GRP_FANNORMAAL=8
GRP_FANHOOG=9
GRP_BEVOCHTIGER=10
GRP_DAGVERLICHTING=11

#SENSORS
TAP_WOONKAMER=2
TAP_KEUKEN=31
TAP_VOORDEUR=32
TAP_SLAAPKAMERDEUR=33
TAP_SLAAPKAMERBED=34
TAP_KANTOOR=35
TAP_BADKAMER=36
MOT_WOONKAMER_MOT=7
MOT_WOONKAMER_EXTRA=8
MOT_WOONKAMER_TEMP=6
MOT_EETKAMER_MOT=41
MOT_EETKAMER_EXTRA=42
MOT_EETKAMER_TEMP=40
MOT_KEUKEN_MOT=12
MOT_KEUKEN_EXTRA=13
MOT_KEUKEN_TEMP=11
MOT_HAL_MOT=18
MOT_HAL_EXTRA=19
MOT_HAL_TEMP=17
MOT_SLAAPKAMER_MOT=16
MOT_SLAAPKAMER_EXTRA=20
MOT_SLAAPKAMER_TEMP=15
MOT_KANTOOR_MOT=26
MOT_KANTOOR_MOT=27
MOT_KANTOOR_TEMP=25
MOT_TOILET_MOT=22
MOT_TOILET_EXTRA=23
MOT_TOILET_TEMP=21
MOT_BADKAMER_MOT=30
MOT_BADKAMER_EXTRA=37
MOT_BADKAMER_TEMP=39
REMOTE=9
TRG_WOONKAMER=4

echo "$(date): Script started with IP ${HUE_IP} and used ${HUE_USER}" >> HueBridgeLog

#curl -s -H "Accept: application/json" -X GET http://${HUE_IP}/api/${HUE_USER}/
#curl -s -H "Accept: application/json" -X PUT --data '{"on":true,"bri": 150,"sat": 150,"hue":15000,"transitiontime":50}' http://${HUE_IP}/api/${HUE_USER}/groups/${GRP_KEUKEN}/action
#curl -s -H "Accept: application/json" -X PUT --data '[{"address": "/config/localtime", "operator": "in", "value": "T05:00:00/T00:00:00"},{"address": "/sensors/57/state/presence","operator": "eq","value": "true"},{"address": "/sensors/57/state/presence","operator": "dx"},{"address": "/sensors/55/state/status","operator": "lt","value": "1"},{"address": "/sensors/42/state/dark","operator": "eq","value": "true"}]' http://${HUE_IP}/api/${HUE_USER}/rules/1/conditions

#curl -s -H "Accept: application/json" -X PUT --data '{"conditions": [{"address": "/config/localtime","operator": "in","value": "T06:00:00/T00:00:00"}, {"address": "/sensors/57/state/presence","operator": "eq","value": "true"}, {"address": "/sensors/57/state/presence","operator": "dx"}, {"address": "/sensors/55/state/status","operator": "lt","value": "1"}, {"address": "/sensors/42/state/dark","operator": "eq","value": "true"}]}' http://${HUE_IP}/api/${HUE_USER}/rules/1/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.day-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/57/state/presence","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "lY5rBuP7YPzNSxR"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }},{"address":"/sensors/55/state","method":"PUT","body":{     "status": 1    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/1/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.day-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/2/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.night-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/57/state/presence","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/3/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.night-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/4/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.dim","conditions":[{"address":"/sensors/57/state/presence","operator":"eq","value":"false"},{"address":"/sensors/57/state/presence","operator":"ddx","value":"PT00:09:15"}],"actions":[{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{     "storelightstate": true    }},{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/1/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/groups/11/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/55/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/5/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.recover","conditions":[{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/57/state/presence","operator":"dx"},{"address":"/sensors/55/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"MTbIDhIx2IZMfC7"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"WeQ3FZfS5MkVLPY"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/6/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.off","conditions":[{"address":"/sensors/57/state/presence","operator":"eq","value":"false"},{"address":"/sensors/55/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/55/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/groups/11/action","method":"PUT","body":{"on":false}},{"address":"/sensors/55/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/7/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.arm","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/groups/11/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/57/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/55/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/8/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.2","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "lY5rBuP7YPzNSxR"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/9/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.4","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "kbwTjMUg7yd-fCn"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "1G3OM-y5bQ76SaI"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/10/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.3","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "saFtgZUq4Mwaq-x"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/11/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.1","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "Y1efqVouGJOT-Rt"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "hXSwGDA1l5MBXpc"    }},{"address":"/groups/2/action","method":"PUT","body":{     "scene": "EzSej7m2oRuERr4"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/12/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.day-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/4/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/13/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.day-dark-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{       "scene": "JpsE2311TGWeCc4"      }},{"address":"/groups/1/action","method":"PUT","body":{       "scene": "lY5rBuP7YPzNSxR"      }},{"address":"/sensors/58/state","method":"PUT","body":{       "status": 1      }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/14/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.night-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/7/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/15/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.night-dark-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/16/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.dim","conditions":[{"address":"/sensors/2/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/1/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{"storelightstate":true}},{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/11/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/58/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/17/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.recover","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/4/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"WeQ3FZfS5MkVLPY"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"MTbIDhIx2IZMfC7"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/18/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.off","owner":"erikvennink","created":"2016-12-05T18:44:57","lasttriggered":"2016-12-29T07:32:01","timestriggered":76,"status":"enabled","recycle":true,"conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/58/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/58/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"on":false}},{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/19/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.arm","owner":"erikvennink","created":"2016-12-05T18:44:57","lasttriggered":"2016-12-29T07:46:54","timestriggered":94,"status":"enabled","recycle":true,"conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/groups/11/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/20/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.1","owner":"erikvennink","created":"2016-12-05T18:47:22","lasttriggered":"2016-12-27T17:03:01","timestriggered":6,"status":"enabled","recycle":false,"conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "EzSej7m2oRuERr4"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "bADIK9D239yXKxM"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/21/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.2","owner":"erikvennink","created":"2016-12-05T18:47:22","lasttriggered":"2016-12-27T16:01:09","timestriggered":8,"status":"enabled","recycle":false,"conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "0d1dLNjXYNfh8yJ"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "4sNTC8Cj2qj3nuG"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/22/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.3","owner":"erikvennink","created":"2016-12-05T18:47:22","lasttriggered":"2016-12-17T11:17:16","timestriggered":3,"status":"enabled","recycle":false,"conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "0d1dLNjXYNfh8yJ"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "bADIK9D239yXKxM"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/23/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.4","owner":"erikvennink","created":"2016-12-05T18:47:22","lasttriggered":"none","timestriggered":0,"status":"enabled","recycle":false,"conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "OY3tqQq0Hhibo5k"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "bADIK9D239yXKxM"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/24/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.day-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/25/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.day-dark-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/26/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.night-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/27/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.night-dark-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/28/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.dim","conditions":[{"address":"/sensors/31/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/2/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/2GrJxtuWsskEq8S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/2/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/59/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/29/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.recover","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"2GrJxtuWsskEq8S"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/30/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/59/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/59/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"on":false}},{"address":"/sensors/59/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/31/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.arm","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/59/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/32/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on0","conditions":[{"address":"/sensors/60/state/status","operator":"lt","value":"1"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"sCxmmmZ--4QP4RI"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/33/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on1","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"1"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/34/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on2","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"2"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":3}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/35/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on3","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"3"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":4}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/36/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on4","conditions":[{"address":"/sensors/60/state/status","operator":"gt","value":"3"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{         "scene" : "kbwTjMUg7yd-fCn"       }},{"address":"/sensors/60/state","method":"PUT","body":{         "status" : 0       }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/37/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":-30}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/38/
#curl -s -H "Accept: application/json" -X PUT --data ' ' http://${HUE_IP}/api/${HUE_USER}/rules/39/




#curl -s -H "Accept: application/json" -X GET http://${HUE_IP}/api/${HUE_USER}/rules/1/conditions/
#curl -s -H "Accept: application/json" -X GET http://${HUE_IP}/api/${HUE_USER}/rules/1/actions/


#curl -s -silent -H "Accept: application/json" -X PUT --data '{"on":true}' http://${HUE_IP}/api/${HUE_USER}/sensors/41/config

echo "$(date): Script finished succesfully" >> HueBridgeLog
