#!/bin/bash

HUE_IP=$(curl https://www.meethue.com/api/nupnp 2> /dev/null | jq -r ".[0].internalipaddress")
HUE_USER=erikvennink

#GROUPS
GRP_WOONKAMER=1
GRP_KEUKEN=2
GRP_HAL=3
GRP_SLAAPKAMER=4
GRP_KANTOOR=5
GRP_TOILET=6
GRP_BADKAMER=7
GRP_FANNORMAAL=8
GRP_FANHOOG=9
GRP_BEVOCHTIGER=10
GRP_DAGVERLICHTING=11
PRESENCE=57

#SENSORS
TAP_WOONKAMER=2
TAP_KEUKEN=31
TAP_VOORDEUR=32
TAP_SLAAPKAMERDEUR=33
TAP_SLAAPKAMERBED=34
TAP_KANTOOR=35
TAP_BADKAMER=36
MOT_WOONKAMER_MOT=7
MOT_WOONKAMER_EXTRA=8
MOT_WOONKAMER_TEMP=6
MOT_EETKAMER_MOT=41
MOT_EETKAMER_EXTRA=42
MOT_EETKAMER_TEMP=40
MOT_KEUKEN_MOT=12
MOT_KEUKEN_EXTRA=13
MOT_KEUKEN_TEMP=11
MOT_HAL_MOT=18
MOT_HAL_EXTRA=19
MOT_HAL_TEMP=17
MOT_SLAAPKAMER_MOT=16
MOT_SLAAPKAMER_EXTRA=20
MOT_SLAAPKAMER_TEMP=15
MOT_KANTOOR_MOT=26
MOT_KANTOOR_MOT=27
MOT_KANTOOR_TEMP=25
MOT_TOILET_MOT=22
MOT_TOILET_EXTRA=23
MOT_TOILET_TEMP=21
MOT_BADKAMER_MOT=30
MOT_BADKAMER_EXTRA=37
MOT_BADKAMER_TEMP=39
REMOTE=9
TRG_WOONKAMER=4

echo "$(date): Script started with IP ${HUE_IP} and used ${HUE_USER}" >> HueBridgeLog

i="1"

while [ $i -lt 125 ]
do
curl -s -H "Accept: application/json" -X DELETE http://${HUE_IP}/api/${HUE_USER}/rules/$i; echo
i=$[$i+1]
done

#Combined rules for motion in the living room, dining room, kitchen and hallway
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionWoonkamer.always-on","conditions":[{"address":"/sensors/7/state/presence","operator":"eq","value":"true"},{"address":"/sensors/7/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/sensors/4/state","method":"PUT","body":{"presence":true}},{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionEetkamer.always-on","conditions":[{"address":"/sensors/41/state/presence","operator":"eq","value":"true"},{"address":"/sensors/41/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene": "JpsE2311TGWeCc4"}},{"address":"/sensors/4/state","method":"PUT","body":{"presence":true}},{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.always-on","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/sensors/4/state","method":"PUT","body":{"presence":true}},{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.always-on","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene": "JpsE2311TGWeCc4"}},{"address":"/sensors/4/state","method":"PUT","body":{"presence":true}},{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.always-on","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.always-on","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.always-on","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.always-on","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/57/state","method":"PUT","body":{"presence":true}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionWoonkamer.always-off","conditions":[{"address":"/sensors/7/state/presence","operator":"eq","value":"false"},{"address":"/sensors/7/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{"presence":false}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionEetkamer.always-off","conditions":[{"address":"/sensors/41/state/presence","operator":"eq","value":"false"},{"address":"/sensors/41/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{"presence":false}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.always-off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{"presence":false}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.always-off","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"false"},{"address":"/sensors/18/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{"presence": false}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Living room lights based on combined rules
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.day-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/4/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.day-dark-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/groups/1/action","method":"PUT","body":{"scene": "lY5rBuP7YPzNSxR"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.night-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/7/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.night-dark-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.dim","conditions":[{"address":"/sensors/2/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/1/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{"storelightstate":true}},{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/11/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/58/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.recover","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/4/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"WeQ3FZfS5MkVLPY"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"MTbIDhIx2IZMfC7"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.off","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/58/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/58/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"on":false}},{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.arm","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/groups/11/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.dim-backup","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/1/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{"storelightstate":true}},{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/11/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/58/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionCombined.dark-off","conditions":[{"address":"/sensors/8/state/lightlevel","operator":"gt","value":"22500"},{"address":"/sensors/8/state/lightlevel","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"on": false}},{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Kitchen lights based on Kitchen motion
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.day-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.day-dark-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.night-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.night-dark-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.dim","conditions":[{"address":"/sensors/31/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/2/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/2GrJxtuWsskEq8S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/2/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/59/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.recover","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"2GrJxtuWsskEq8S"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/59/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/59/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"on":false}},{"address":"/sensors/59/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.arm","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/59/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.dim-backup","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/2/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/2GrJxtuWsskEq8S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/2/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/59/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKeuken.fan-off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:25:00"}],"actions":[{"address":"/groups/9/action","method":"PUT","body":{"on": false}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Hallway lights based on Hallway motion
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.day-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.day-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.night-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"1GklgUAlcR2oLb4"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.night-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"1GklgUAlcR2oLb4"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.dim","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"false"},{"address":"/sensors/18/state/presence","operator":"ddx","value":"PT00:04:15"},{"address":"/groups/3/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/wuApZ4OkJebpJcK","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/3/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/61/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.recover","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"},{"address":"/sensors/61/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"wuApZ4OkJebpJcK"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.off","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"false"},{"address":"/sensors/61/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/61/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"on":false}},{"address":"/sensors/61/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionHal.arm","conditions":[{"address":"/groups/3/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/18/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/61/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Bedroom lights based on Bedroom motion
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.day-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T07:00:00/T21:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"NtOfWztY1MA9EPO"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.day-dark-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T07:00:00/T21:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"NtOfWztY1MA9EPO"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.night-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T21:00:00/T07:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"GvAGCIp0mS2VNDF"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.night-dark-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T21:00:00/T07:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"GvAGCIp0mS2VNDF"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.dim","conditions":[{"address":"/sensors/33/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/34/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/16/state/presence","operator":"eq","value":"false"},{"address":"/sensors/16/state/presence","operator":"ddx","value":"PT00:04:15"},{"address":"/groups/4/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/sDthsHfhL4-QTB6","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/4/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/62/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.recover","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"},{"address":"/sensors/62/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"sDthsHfhL4-QTB6"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.off","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"false"},{"address":"/sensors/62/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/62/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"on":false}},{"address":"/sensors/62/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.arm","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/16/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/62/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSlaapkamer.dim-backup","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"false"},{"address":"/sensors/16/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/4/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/sDthsHfhL4-QTB6","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/4/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/62/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Office lights based on Office motion
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.day-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T08:00:00/T23:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.day-dark-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T08:00:00/T23:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.night-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T23:00:00/T08:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.night-dark-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T23:00:00/T08:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.dim","conditions":[{"address":"/sensors/35/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/26/state/presence","operator":"eq","value":"false"},{"address":"/sensors/26/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/5/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/Dv0kxgYj3itnw3S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/5/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/63/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.recover","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"},{"address":"/sensors/63/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"Dv0kxgYj3itnw3S"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.off","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"false"},{"address":"/sensors/63/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/63/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"on":false}},{"address":"/sensors/63/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.arm","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/26/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/63/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionKantoor.dim-backup","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"false"},{"address":"/sensors/26/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/5/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/Dv0kxgYj3itnw3S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/5/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/63/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Toilet lights based on Toilets motion
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.day-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"BPQH6GSVfW-RD8J"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.day-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"BPQH6GSVfW-RD8J"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.night-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"B0LjUvMLeQlQHSr"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.night-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"B0LjUvMLeQlQHSr"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.dim","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"false"},{"address":"/sensors/22/state/presence","operator":"ddx","value":"PT00:04:15"},{"address":"/groups/6/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/tmO1lCefZpNdoZ1","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/6/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/64/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.recover","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"},{"address":"/sensors/64/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"tmO1lCefZpNdoZ1"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.off","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"false"},{"address":"/sensors/64/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/64/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"on":false}},{"address":"/sensors/64/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionToilet.arm","conditions":[{"address":"/groups/6/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/22/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/64/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Bathroom lights based on Bathroom motion
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.day-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T05:00:00/T17:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"cjlVEu8YeW6agwg"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.day-dark-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T05:00:00/T17:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"cjlVEu8YeW6agwg"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.night-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T17:00:00/T05:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"Y8EQi91YHYhBTiT"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.night-dark-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T17:00:00/T05:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"Y8EQi91YHYhBTiT"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.dim","conditions":[{"address":"/sensors/36/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/30/state/presence","operator":"eq","value":"false"},{"address":"/sensors/30/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/7/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/--84gUFKu7EVuFe","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/7/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/3/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.recover","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"},{"address":"/sensors/3/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"--84gUFKu7EVuFe"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.off","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"false"},{"address":"/sensors/3/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/3/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"on":false}},{"address":"/sensors/3/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.arm","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/30/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/3/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionBadkamer.dim-backup","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"false"},{"address":"/sensors/30/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/7/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/--84gUFKu7EVuFe","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/7/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/3/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Living room lights based on Living TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapWoonkamer.1","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"Y1efqVouGJOT-Rt"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"hXSwGDA1l5MBXpc"}},{"address":"/groups/2/action","method":"PUT","body":{"scene":"EzSej7m2oRuERr4"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapWoonkamer.2","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapWoonkamer.3","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"saFtgZUq4Mwaq-x"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapWoonkamer.4","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Kitchen lights based on Kitchen TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKeuken.1","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"EzSej7m2oRuERr4"}},{"address":"/groups/9/action","method":"PUT","body":{"scene":"bADIK9D239yXKxM"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKeuken.2","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/groups/9/action","method":"PUT","body":{"scene":"4sNTC8Cj2qj3nuG"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKeuken.3","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/groups/9/action","method":"PUT","body":{"scene":"bADIK9D239yXKxM"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKeuken.4","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/groups/9/action","method":"PUT","body":{"scene":"bADIK9D239yXKxM"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Hallway lights based on Front Door TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapVoordeur.1","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/0/action","method":"PUT","body":{"scene":"f-1qNW-Ae1skKc9"}},{"address":"/sensors/57/state","method":"PUT","body":{"presence":false}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapVoordeur.2","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/8/action","method":"PUT","body":{"scene":"667MapdzovQFaJH"}},{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapVoordeur.3","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/8/action","method":"PUT","body":{"scene":"667MapdzovQFaJH"}},{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapVoordeur.4","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/8/action","method":"PUT","body":{"scene":"667MapdzovQFaJH"}},{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Bedroom lights based on Bedroom Door TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerDeur.1","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"097zsIC6rICjxtE"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"Zta7BSqFjvGEpf8"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerDeur.2","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"Fxnq1qO5qQWD5Uz"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerDeur.3","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"NtOfWztY1MA9EPO"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerDeur.4","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"GvAGCIp0mS2VNDF"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Bedroom lights based on Bedroom Bed TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerBed.1","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"FVM7A2euJuX1VuT"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerBed.2","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"Fxnq1qO5qQWD5Uz"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerBed.3","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"NtOfWztY1MA9EPO"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapSlaapkamerBed.4","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"GvAGCIp0mS2VNDF"}},{"address":"/groups/10/action","method":"PUT","body":{"scene":"gMVEnvipzWxPTRU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Office lights based on Office TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKantoor.1","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"kZOKfvQ2ePZODoc"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKantoor.2","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKantoor.3","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapKantoor.4","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

#Bathroom lights based on Bathroom TAP
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapBadkamer.3","conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"Y8EQi91YHYhBTiT"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapBadkamer.2","conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"cjlVEu8YeW6agwg"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapBadkamer.4","conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"cjlVEu8YeW6agwg"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"TapBadkamer.1","conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"jnVpHixng-CvAH5"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer Switch 9 on0","conditions":[{"address":"/sensors/60/state/status","operator":"lt","value":"1"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"sCxmmmZ--4QP4RI"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer Switch 9 on1","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"1"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer Switch 9 on2","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"2"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":3}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer Switch 9 on3","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"3"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":4}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer Switch 9 on4","conditions":[{"address":"/sensors/60/state/status","operator":"gt","value":"3"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{         "scene" : "kbwTjMUg7yd-fCn"       }},{"address":"/sensors/60/state","method":"PUT","body":{         "status" : 0       }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":-30}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3001"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":-56}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3003"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.2 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"2000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":30}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.2 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"2001"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":56}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.2 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"2003"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer 9.4 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"4000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/sensors/60/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo
curl -s -H "Accept: application/json" -X POST --data '{"name":"Dimmer Switch 9 reset timer","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/schedules/1","method":"PUT","body":{"status":"enabled"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/; echo

echo "$(date): Script finished succesfully" >> HueBridgeLog
