#!/bin/bash

HUE_IP=$(curl https://www.meethue.com/api/nupnp 2> /dev/null | jq -r ".[0].internalipaddress")
HUE_USER=erikvennink

#GROUPS + SCENES
GRP_WOONKAMER=1
GRP_KEUKEN=2
GRP_HAL=3
GRP_SLAAPKAMER=4
GRP_KANTOOR=5
GRP_TOILET=6
GRP_BADKAMER=7
GRP_FANNORMAAL=8
GRP_FANHOOG=9
GRP_BEVOCHTIGER=10
GRP_DAGVERLICHTING=11

#SENSORS
TAP_WOONKAMER=2
TAP_KEUKEN=31
TAP_VOORDEUR=32
TAP_SLAAPKAMERDEUR=33
TAP_SLAAPKAMERBED=34
TAP_KANTOOR=35
TAP_BADKAMER=36
MOT_WOONKAMER_MOT=7
MOT_WOONKAMER_EXTRA=8
MOT_WOONKAMER_TEMP=6
MOT_EETKAMER_MOT=41
MOT_EETKAMER_EXTRA=42
MOT_EETKAMER_TEMP=40
MOT_KEUKEN_MOT=12
MOT_KEUKEN_EXTRA=13
MOT_KEUKEN_TEMP=11
MOT_HAL_MOT=18
MOT_HAL_EXTRA=19
MOT_HAL_TEMP=17
MOT_SLAAPKAMER_MOT=16
MOT_SLAAPKAMER_EXTRA=20
MOT_SLAAPKAMER_TEMP=15
MOT_KANTOOR_MOT=26
MOT_KANTOOR_MOT=27
MOT_KANTOOR_TEMP=25
MOT_TOILET_MOT=22
MOT_TOILET_EXTRA=23
MOT_TOILET_TEMP=21
MOT_BADKAMER_MOT=30
MOT_BADKAMER_EXTRA=37
MOT_BADKAMER_TEMP=39
REMOTE=9
TRG_WOONKAMER=4

echo "$(date): Script started with IP ${HUE_IP} and used ${HUE_USER}" >> HueBridgeLog

x=1
while x < 2; do
echo x
x=x+1
done

curl -s -H "Accept: application/json" -X DELETE http://${HUE_IP}/api/${HUE_USER}/rules/1
curl -s -H "Accept: application/json" -X DELETE http://${HUE_IP}/api/${HUE_USER}/rules/2
curl -s -H "Accept: application/json" -X DELETE http://${HUE_IP}/api/${HUE_USER}/rules/3

curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSensor 41.day-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/57/state/presence","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "lY5rBuP7YPzNSxR"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }},{"address":"/sensors/55/state","method":"PUT","body":{     "status": 1    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSensor 41.day-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/
curl -s -H "Accept: application/json" -X POST --data '{"name":"MotionSensor 41.night-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/57/state/presence","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.night-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"eq","value":"true"},{"address":"/sensors/42/state/dark","operator":"dx"},{"address":"/sensors/55/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/4/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.dim","conditions":[{"address":"/sensors/57/state/presence","operator":"eq","value":"false"},{"address":"/sensors/57/state/presence","operator":"ddx","value":"PT00:09:15"}],"actions":[{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{     "storelightstate": true    }},{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/1/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/groups/11/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/55/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/5/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.recover","conditions":[{"address":"/sensors/57/state/presence","operator":"eq","value":"true"},{"address":"/sensors/57/state/presence","operator":"dx"},{"address":"/sensors/55/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"MTbIDhIx2IZMfC7"}},{"address":"/groups/11/action","method":"PUT","body":{"scene":"WeQ3FZfS5MkVLPY"}},{"address":"/sensors/55/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/6/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.off","conditions":[{"address":"/sensors/57/state/presence","operator":"eq","value":"false"},{"address":"/sensors/55/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/55/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/groups/11/action","method":"PUT","body":{"on":false}},{"address":"/sensors/55/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/7/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.arm","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/groups/11/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/57/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/55/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/8/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.2","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "lY5rBuP7YPzNSxR"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/9/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.4","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "kbwTjMUg7yd-fCn"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "1G3OM-y5bQ76SaI"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/10/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.3","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "saFtgZUq4Mwaq-x"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/11/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 2.1","conditions":[{"address":"/sensors/2/state/lastupdated","operator":"dx"},{"address":"/sensors/2/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{     "scene": "Y1efqVouGJOT-Rt"    }},{"address":"/groups/11/action","method":"PUT","body":{     "scene": "hXSwGDA1l5MBXpc"    }},{"address":"/groups/2/action","method":"PUT","body":{     "scene": "EzSej7m2oRuERr4"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/12/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.day-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/4/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"JpsE2311TGWeCc4"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/13/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.day-dark-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{       "scene": "JpsE2311TGWeCc4"      }},{"address":"/groups/1/action","method":"PUT","body":{       "scene": "lY5rBuP7YPzNSxR"      }},{"address":"/sensors/58/state","method":"PUT","body":{       "status": 1      }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/14/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.night-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/7/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/15/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.night-dark-on","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"eq","value":"true"},{"address":"/sensors/8/state/dark","operator":"dx"},{"address":"/sensors/58/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"1G3OM-y5bQ76SaI"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/16/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.dim","conditions":[{"address":"/sensors/2/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/1/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{"storelightstate":true}},{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/11/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/58/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/17/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.recover","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"true"},{"address":"/sensors/4/state/presence","operator":"dx"},{"address":"/sensors/58/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene":"WeQ3FZfS5MkVLPY"}},{"address":"/groups/1/action","method":"PUT","body":{"scene":"MTbIDhIx2IZMfC7"}},{"address":"/sensors/58/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/18/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.off","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/58/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/58/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"on":false}},{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/19/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.arm","conditions":[{"address":"/groups/1/state/any_on","operator":"eq","value":"false"},{"address":"/groups/11/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/58/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/20/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.1","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "EzSej7m2oRuERr4"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "bADIK9D239yXKxM"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/21/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.2","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "0d1dLNjXYNfh8yJ"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "4sNTC8Cj2qj3nuG"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/22/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.3","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "0d1dLNjXYNfh8yJ"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "bADIK9D239yXKxM"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/23/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 31.4","conditions":[{"address":"/sensors/31/state/lastupdated","operator":"dx"},{"address":"/sensors/31/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{     "scene": "OY3tqQq0Hhibo5k"    }},{"address":"/groups/9/action","method":"PUT","body":{     "scene": "bADIK9D239yXKxM"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/24/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.day-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/25/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.day-dark-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"0d1dLNjXYNfh8yJ"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/26/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.night-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/27/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.night-dark-on","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"eq","value":"true"},{"address":"/sensors/13/state/dark","operator":"dx"},{"address":"/sensors/59/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"OY3tqQq0Hhibo5k"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/28/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.dim","conditions":[{"address":"/sensors/31/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/2/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/2GrJxtuWsskEq8S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/2/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/59/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/29/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.recover","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"},{"address":"/sensors/59/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"scene":"2GrJxtuWsskEq8S"}},{"address":"/sensors/59/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/30/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/59/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/59/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/2/action","method":"PUT","body":{"on":false}},{"address":"/sensors/59/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/31/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.arm","conditions":[{"address":"/groups/2/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/59/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/32/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on0","conditions":[{"address":"/sensors/60/state/status","operator":"lt","value":"1"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"sCxmmmZ--4QP4RI"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/33/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on1","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"1"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/34/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on2","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"2"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"kbwTjMUg7yd-fCn"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":3}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/35/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on3","conditions":[{"address":"/sensors/60/state/status","operator":"eq","value":"3"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"scene":"lY5rBuP7YPzNSxR"}},{"address":"/sensors/60/state","method":"PUT","body":{"status":4}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/36/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 on4","conditions":[{"address":"/sensors/60/state/status","operator":"gt","value":"3"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"1000"},{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{         "scene" : "kbwTjMUg7yd-fCn"       }},{"address":"/sensors/60/state","method":"PUT","body":{         "status" : 0       }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/37/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":-30}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/38/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3001"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":-56}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/39/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.3 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"3003"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/40/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.2 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"2000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":30}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/41/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.2 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"2001"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"transitiontime":9,"bri_inc":56}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/42/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.2 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"2003"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"bri_inc":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/43/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer 9.4 Lights","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"},{"address":"/sensors/9/state/buttonevent","operator":"eq","value":"4000"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{"on":false}},{"address":"/sensors/60/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/44/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Dimmer Switch 9 reset timer","conditions":[{"address":"/sensors/9/state/lastupdated","operator":"dx"}],"actions":[{"address":"/schedules/1","method":"PUT","body":{"status":"enabled"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/45/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 32.3","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/8/action","method":"PUT","body":{     "scene": "667MapdzovQFaJH"    }},{"address":"/groups/3/action","method":"PUT","body":{     "scene": "4F1FeN6bz4pvnTB"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/46/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 32.2","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/8/action","method":"PUT","body":{     "scene": "667MapdzovQFaJH"    }},{"address":"/groups/3/action","method":"PUT","body":{     "scene": "4F1FeN6bz4pvnTB"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/47/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 32.4","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/8/action","method":"PUT","body":{     "scene": "667MapdzovQFaJH"    }},{"address":"/groups/3/action","method":"PUT","body":{     "scene": "4F1FeN6bz4pvnTB"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/48/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 32.1","conditions":[{"address":"/sensors/32/state/lastupdated","operator":"dx"},{"address":"/sensors/32/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/0/action","method":"PUT","body":{     "scene": "f-1qNW-Ae1skKc9"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/49/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.day-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/50/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.day-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"4F1FeN6bz4pvnTB"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/51/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.night-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"1GklgUAlcR2oLb4"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/52/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.night-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"eq","value":"true"},{"address":"/sensors/19/state/dark","operator":"dx"},{"address":"/sensors/61/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"1GklgUAlcR2oLb4"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/53/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.dim","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"false"},{"address":"/sensors/18/state/presence","operator":"ddx","value":"PT00:04:15"},{"address":"/groups/3/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/wuApZ4OkJebpJcK","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/3/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/61/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/54/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.recover","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"},{"address":"/sensors/61/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"scene":"wuApZ4OkJebpJcK"}},{"address":"/sensors/61/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/55/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.off","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"false"},{"address":"/sensors/61/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/61/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/3/action","method":"PUT","body":{"on":false}},{"address":"/sensors/61/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/56/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.arm","conditions":[{"address":"/groups/3/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/18/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/61/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/57/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 33.3","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "NtOfWztY1MA9EPO"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/58/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 33.2","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "Fxnq1qO5qQWD5Uz"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/59/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 33.4","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "GvAGCIp0mS2VNDF"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/60/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 33.1","conditions":[{"address":"/sensors/33/state/lastupdated","operator":"dx"},{"address":"/sensors/33/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "097zsIC6rICjxtE"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "Zta7BSqFjvGEpf8"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/61/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 34.3","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "NtOfWztY1MA9EPO"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/62/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 34.2","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "Fxnq1qO5qQWD5Uz"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/63/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 34.1","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "FVM7A2euJuX1VuT"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/64/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 34.4","conditions":[{"address":"/sensors/34/state/lastupdated","operator":"dx"},{"address":"/sensors/34/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{     "scene": "GvAGCIp0mS2VNDF"    }},{"address":"/groups/10/action","method":"PUT","body":{     "scene": "gMVEnvipzWxPTRU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/65/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.day-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T07:00:00/T21:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"NtOfWztY1MA9EPO"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/66/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.day-dark-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T07:00:00/T21:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"NtOfWztY1MA9EPO"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/67/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.night-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T21:00:00/T07:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"GvAGCIp0mS2VNDF"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/68/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.night-dark-on","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T21:00:00/T07:00:00"},{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"eq","value":"true"},{"address":"/sensors/20/state/dark","operator":"dx"},{"address":"/sensors/62/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"GvAGCIp0mS2VNDF"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/69/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.dim","conditions":[{"address":"/sensors/33/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/34/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/16/state/presence","operator":"eq","value":"false"},{"address":"/sensors/16/state/presence","operator":"ddx","value":"PT00:04:15"},{"address":"/groups/4/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/sDthsHfhL4-QTB6","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/4/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/62/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/70/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.recover","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"true"},{"address":"/sensors/16/state/presence","operator":"dx"},{"address":"/sensors/62/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"sDthsHfhL4-QTB6"}},{"address":"/sensors/62/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/71/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.off","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"false"},{"address":"/sensors/62/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/62/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"on":false}},{"address":"/sensors/62/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/72/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.arm","conditions":[{"address":"/groups/4/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/16/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/62/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/73/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 35.3","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{     "scene": "5gxSo0FhwjqVUJU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/74/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 35.2","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{     "scene": "5gxSo0FhwjqVUJU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/75/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 35.4","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{     "scene": "5gxSo0FhwjqVUJU"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/76/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 35.1","conditions":[{"address":"/sensors/35/state/lastupdated","operator":"dx"},{"address":"/sensors/35/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{     "scene": "kZOKfvQ2ePZODoc"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/77/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.day-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T08:00:00/T23:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/78/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.day-dark-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T08:00:00/T23:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/79/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.night-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T23:00:00/T08:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/80/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.night-dark-on","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T23:00:00/T08:00:00"},{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"eq","value":"true"},{"address":"/sensors/27/state/dark","operator":"dx"},{"address":"/sensors/63/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"5gxSo0FhwjqVUJU"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/81/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.dim","conditions":[{"address":"/sensors/35/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/26/state/presence","operator":"eq","value":"false"},{"address":"/sensors/26/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/5/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/Dv0kxgYj3itnw3S","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/5/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/63/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/82/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.recover","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"true"},{"address":"/sensors/26/state/presence","operator":"dx"},{"address":"/sensors/63/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"scene":"Dv0kxgYj3itnw3S"}},{"address":"/sensors/63/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/83/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.off","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"false"},{"address":"/sensors/63/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/63/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/5/action","method":"PUT","body":{"on":false}},{"address":"/sensors/63/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/84/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.arm","conditions":[{"address":"/groups/5/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/26/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/63/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/85/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.day-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"BPQH6GSVfW-RD8J"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/86/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.day-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T06:00:00/T00:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"BPQH6GSVfW-RD8J"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/87/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.night-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"B0LjUvMLeQlQHSr"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/88/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.night-dark-on","conditions":[{"address":"/config/localtime","operator":"in","value":"T00:00:00/T06:00:00"},{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"eq","value":"true"},{"address":"/sensors/23/state/dark","operator":"dx"},{"address":"/sensors/64/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"B0LjUvMLeQlQHSr"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/89/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.dim","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"false"},{"address":"/sensors/22/state/presence","operator":"ddx","value":"PT00:04:15"},{"address":"/groups/6/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/tmO1lCefZpNdoZ1","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/6/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/64/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/90/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.recover","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"true"},{"address":"/sensors/22/state/presence","operator":"dx"},{"address":"/sensors/64/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"scene":"tmO1lCefZpNdoZ1"}},{"address":"/sensors/64/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/91/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.off","conditions":[{"address":"/sensors/22/state/presence","operator":"eq","value":"false"},{"address":"/sensors/64/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/64/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/6/action","method":"PUT","body":{"on":false}},{"address":"/sensors/64/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/92/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 22.arm","conditions":[{"address":"/groups/6/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/22/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/64/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/93/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 36.3","conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"17"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{     "scene": "Y8EQi91YHYhBTiT"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/94/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 36.2”,”conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"16"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{     "scene": "cjlVEu8YeW6agwg"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/95/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 36.4","conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"18"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{     "scene": "cjlVEu8YeW6agwg"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/96/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"Tap 36.1”,”conditions":[{"address":"/sensors/36/state/lastupdated","operator":"dx"},{"address":"/sensors/36/state/buttonevent","operator":"eq","value":"34"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{     "scene": "jnVpHixng-CvAH5"    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/97/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.day-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T05:00:00/T17:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"cjlVEu8YeW6agwg"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]},' http://${HUE_IP}/api/${HUE_USER}/rules/98/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.day-dark-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T05:00:00/T17:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"cjlVEu8YeW6agwg"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/99/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.night-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T17:00:00/T05:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"Y8EQi91YHYhBTiT"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/100/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.night-dark-on","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/config/localtime","operator":"in","value":"T17:00:00/T05:00:00"},{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"eq","value":"true"},{"address":"/sensors/37/state/dark","operator":"dx"},{"address":"/sensors/3/state/status","operator":"lt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"Y8EQi91YHYhBTiT"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/101/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.dim","conditions":[{"address":"/sensors/36/state/buttonevent","operator":"gt","value":"20"},{"address":"/sensors/30/state/presence","operator":"eq","value":"false"},{"address":"/sensors/30/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/7/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/--84gUFKu7EVuFe","method":"PUT","body":{"storelightstate":true}},{"address":"/groups/7/action","method":"PUT","body":{"bri_inc":-128}},{"address":"/sensors/3/state","method":"PUT","body":{"status":2}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/102/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.recover","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"true"},{"address":"/sensors/30/state/presence","operator":"dx"},{"address":"/sensors/3/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"scene":"--84gUFKu7EVuFe"}},{"address":"/sensors/3/state","method":"PUT","body":{"status":1}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/103/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.off","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"false"},{"address":"/sensors/3/state/status","operator":"ddx","value":"PT00:00:30"},{"address":"/sensors/3/state/status","operator":"gt","value":"1"}],"actions":[{"address":"/groups/7/action","method":"PUT","body":{"on":false}},{"address":"/sensors/3/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/104/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.arm","conditions":[{"address":"/groups/7/state/any_on","operator":"eq","value":"false"},{"address":"/sensors/30/state/presence","operator":"eq","value":"false"}],"actions":[{"address":"/sensors/3/state","method":"PUT","body":{"status":0}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/105/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.always-on”,”conditions":[{"address":"/sensors/7/state/presence","operator":"eq","value":"true"},{"address":"/sensors/7/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }},{"address":"/sensors/4/state","method":"PUT","body":{     "presence": true    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/106/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.always-on","conditions":[{"address":"/sensors/41/state/presence","operator":"eq","value":"true"},{"address":"/sensors/41/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }},{"address":"/sensors/4/state","method":"PUT","body":{     "presence": true    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/107/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.always-off","conditions":[{"address":"/sensors/7/state/presence","operator":"eq","value":"false"},{"address":"/sensors/7/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{     "presence": false    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/108/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 41.always-off","conditions":[{"address":"/sensors/41/state/presence","operator":"eq","value":"false"},{"address":"/sensors/41/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{     "presence": false    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/109/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.always-on”,”conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"true"},{"address":"/sensors/12/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }},{"address":"/sensors/4/state","method":"PUT","body":{     "presence": true    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/110/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.always-off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{     "presence": false    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/111/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.fan-off","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:25:00"}],"actions":[{"address":"/groups/9/action","method":"PUT","body":{     "on": false    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/112/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.always-on","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"true"},{"address":"/sensors/18/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{     "scene": "JpsE2311TGWeCc4"    }},{"address":"/sensors/4/state","method":"PUT","body":{     "presence": true    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/113/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 18.always-off","conditions":[{"address":"/sensors/18/state/presence","operator":"eq","value":"false"},{"address":"/sensors/18/state/presence","operator":"dx"}],"actions":[{"address":"/sensors/4/state","method":"PUT","body":{     "presence": false    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/114/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 16.dim-backup","conditions":[{"address":"/sensors/16/state/presence","operator":"eq","value":"false"},{"address":"/sensors/16/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/4/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/sDthsHfhL4-QTB6","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/4/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/62/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/115/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.dark-off","conditions":[{"address":"/sensors/8/state/lightlevel","operator":"gt","value":"22500"},{"address":"/sensors/8/state/lightlevel","operator":"dx"}],"actions":[{"address":"/groups/1/action","method":"PUT","body":{       "on": false      }},{"address":"/sensors/58/state","method":"PUT","body":{       "status": 0      }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/116/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 7.dim-backup","conditions":[{"address":"/sensors/4/state/presence","operator":"eq","value":"false"},{"address":"/sensors/4/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/1/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/WeQ3FZfS5MkVLPY","method":"PUT","body":{     "storelightstate": true    }},{"address":"/scenes/MTbIDhIx2IZMfC7","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/11/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/groups/1/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/58/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/117/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 12.dim-backup","conditions":[{"address":"/sensors/12/state/presence","operator":"eq","value":"false"},{"address":"/sensors/12/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/2/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/2GrJxtuWsskEq8S","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/2/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/59/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/118/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 26.dim-backup","conditions":[{"address":"/sensors/26/state/presence","operator":"eq","value":"false"},{"address":"/sensors/26/state/presence","operator":"ddx","value":"PT00:29:15"},{"address":"/groups/5/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/Dv0kxgYj3itnw3S","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/5/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/63/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/119/
curl -s -H "Accept: application/json" -X PUT --data '{"name":"MotionSensor 30.dim-backup","conditions":[{"address":"/sensors/30/state/presence","operator":"eq","value":"false"},{"address":"/sensors/30/state/presence","operator":"ddx","value":"PT00:09:15"},{"address":"/groups/7/state/any_on","operator":"eq","value":"true"}],"actions":[{"address":"/scenes/--84gUFKu7EVuFe","method":"PUT","body":{     "storelightstate": true    }},{"address":"/groups/7/action","method":"PUT","body":{     "bri_inc": -128    }},{"address":"/sensors/3/state","method":"PUT","body":{     "status": 2    }}]}' http://${HUE_IP}/api/${HUE_USER}/rules/120/

#curl -s -H "Accept: application/json" -X DELETE http://${HUE_IP}/api/${HUE_USER}/rules/121

#curl -s -H "Accept: application/json" -X POST --data '{"name":"TEST2","conditions":[{"address":"/sensors/41/state/presence","operator":"eq","value":"true"},{"address":"/sensors/41/state/presence","operator":"dx"}],"actions":[{"address":"/groups/11/action","method":"PUT","body":{"scene": "JpsE2311TGWeCc4"}}]}' http://${HUE_IP}/api/${HUE_USER}/rules/

echo "$(date): Script finished succesfully" >> HueBridgeLog
